import Head from 'next/head'
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

// const Pokemon = ({ pokemonName, classActiveId, id, onClick}) => (
//   <li onClick={()=> onClick({id,pokemonName})} id={id} className={classActiveId === id ? "list-group-item list-group-item-action active" : "list-group-item list-group-item-action false" }>{pokemonName}</li>
// )

const Pokemon = ({ pokemonName, id, url}) => (
  <Link key={id} href={`pokemon/${id}`} passHref><li>{pokemonName}</li></Link>
)

export default function Home() {
  const Router = useRouter();
  console.log("Router", Router);
  
  const [pokemonList, setPokemonList] = useState ([]);
  const [activeIdClick, setActiveIdClick] = useState (null);

  useEffect(() =>{
    const getData = async()=>{
      const response = await fetch('https://pokeapi.co/api/v2/pokemon?limit=10');
      const data = await response.json();
      const { results } = data;
      setPokemonList(results);
      console.log("data ", data);
    }
      getData();
  }, [])

  const handleClick = (e) => {
    console.log(e);
    if (e) {
      // setEmotion(e.target.value);
      setActiveIdClick(e.id);
      // setPokemonUrlSelected(e.id);
      // setPokemonNameSelected(e.pokemonName);
      console.log("click ",e.id);
      // console.log("nama ",e.target.value);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <h1 className={styles.title}>
          Pokemon List
        </h1>
        <ul>
        {pokemonList?.map((pokemon, index) => (
          <Pokemon 
            key={index} 
            pokemonName={pokemon.name}
            id={(index+1)} 
            url={pokemon.url}
          />
        )
        )
        }
        </ul>

        
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
